image: node:latest

# before_script:
#     - npm install

stages:
    - start
    - deploy

start:
  stage: start
  script:
    - echo "installing packages"
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/

deploy:
    stage: deploy
    script:
        - echo "Building application"
        - CI=false
        - npm run build