image: node:latest

# before_script:
#     - npm install
    
install_packages:
  stage: install
  script:
    - echo "installing packages"
    - npm install
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
stages:
    - start

start:
    stage: start
    script:
        - echo "Building application"
        - npm start